version: "1.0"
name: "chefindica-backend"

services:
  api:
    container_name: 'api'
    build: .
    ports: 
      - '8080:8080'

    # a api só pode ser iniciada depois do bd
    depends_on:
      - mysql


    # o banco e a API devem pertencer ao mesmo serviço
    networks:
      - springapimysql-net
    restart: always
    volumes:
      - .m2:/root/.m2
  mysql:
    container_name: 'mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_ROOT_PASSWORD=verysecret'

    # o banco e a API devem pertencer ao mesmo serviço
    networks:
      - springapimysql-net
    restart: always
    ports:
      - '3306:3306'

networks:
  springapimysql-net:
